<?php

class Blog_Templates_Settings_Menu {


    /**
     * Slug of the plugin screen.
     */
    protected $plugin_screen_hook_suffix = null;

    public $menu_slug = 'blog_templates_settings';

    /**
     * Initialize the plugin by loading admin scripts & styles and adding a
     * settings page and menu.
     *
     */
    public function __construct() {

        $plugin = Blog_Templates::get_instance();
        $this->plugin_slug = $plugin->get_plugin_slug();

        // Add the options page and menu item.
        add_action( 'network_admin_menu', array( $this, 'add_admin_menu' ) );

    }


    /**
     * Register the administration menu for this plugin into the WordPress Dashboard menu.
     *
     * @since    1.0.0
     */
    public function add_admin_menu() {
        $this->plugin_screen_hook_suffix = add_submenu_page( 
            'blog_templates_main', 
            __( 'New Blog Templates Settings', 'blog_templates' ), 
            __( 'Settings', 'blog_templates' ), 
            'manage_network', 
            $this->menu_slug, 
            array( $this,'display' ) );

        add_action( 'load-' . $this->plugin_screen_hook_suffix, array( $this, 'process_form' ) );
    }



    /**
     * Render the settings page for this plugin.
     *
     * @since    1.0.0
     */
    public function display() {
        $t = isset( $_GET['t'] ) ? (string) $_GET['t'] : '';
        $settings = nbt_get_settings();

        $updated = isset( $_GET['updated'] ) && 'true' === $_GET['updated'];

        include_once( 'views/settings.php' );
    }

    public function process_form() {
        $model = nbt_get_model();
        $settings = nbt_get_settings();


        if (isset($_POST['save_options'])) {

            if (! wp_verify_nonce($_POST['_nbtnonce'], 'blog_templates-update-options') )
                wp_die( __( 'Whoops! There was a problem with the data you posted. Please go back and try again. (Generated by New Blog Templates)', 'blog_templates' ) );

            $defaults = nbt_get_default_settings();
            $settings['show-registration-templates'] = isset($_POST['show-registration-templates']) ? (int)$_POST['show-registration-templates'] : 0;

            $selection_types = nbt_get_template_selection_types();
            $appearance = isset( $_POST['registration-templates-appearance'] ) && array_key_exists( $_POST['registration-templates-appearance'], $selection_types) 
                ? $_POST['registration-templates-appearance'] 
                : key( $selection_types );
            if ( 'page_showcase' == $appearance && ! empty( $_POST['page-showcase-id'] ) && $page = get_post( absint( $_POST['page-showcase-id'] ) ) ) {

                $settings['registration-templates-appearance'] = $appearance;
                $settings['page-showcase-id'] = $page->ID;
            }
            elseif ( 'page-showcase' !== $appearance ) {
                $settings['registration-templates-appearance'] = $appearance;
            }
            $settings['show-categories-selection'] = isset($_POST['show-categories-selection']) ? $_POST['show-categories-selection'] : 0;

            nbt_update_settings( $settings );

            $this->updated_message =  __( 'Options saved.', 'blog_templates' );
            add_action( 'network_admin_notices', array( &$this, 'show_admin_notice' ) );

            $redirect_to = add_query_arg( 'updated', 'true' );
            wp_redirect( $redirect_to );
            exit;
        }

        if ( isset( $_POST['submit_repair_database'] ) && isset( $_POST['action'] ) && 'repair_database' == $_POST['action' ] ) {

            if ( ! wp_verify_nonce( $_POST['_wpnonce'], 'repair-database' ) )
                return false;

            if ( ! ( isset( $_POST['repair-tables'] ) ) )
                return false;
            
            $model = nbt_get_model();
            $model->create_tables();

        }
    }

    private function render_row( $title, $markup ) {
        ?>
        <tr valign="top">
            <th scope="row"><label for=""><?php echo $title; ?></label></th>
            <td>
                <?php echo $markup; ?>
            </td>
        </tr>
        <?php
    }

}

